Movie_recommendation_system/urls.py
from django.contrib import admin
from django.urls import path,include
from movie import urls
from .views import index,star

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('',index),
    path('movie/',include('movie.urls')),
    path('star',star)
]

movie/urls.py
from django.urls import path, reverse
from . import views

app_name = 'movie'

urlpatterns = [
    # 默认首页
    path('', views.IndexView.as_view(), name='index'),
    # 热门电影
    path('hot', views.PopularMovieView.as_view(), name='hot'),
    # 登录
    path('login', views.LoginView.as_view(), name='login'),
    # 退出
    path('logout', views.UserLogout, name='logout'),
    # 注册
    path('register', views.RegisterView.as_view(), name='register'),
    # 分类查看
    path('tag', views.TagView.as_view(), name='tag'),
    # 搜索功能
    path('search', views.SearchView.as_view(), name='search'),
    # 电影详情页面
    path('detail/<int:pk>', views.MovieDetailView.as_view(), name='detail'),
    # 评分历史页面
    path('history/<int:pk>', views.RatingHistoryView.as_view(),name='history'),
    # 删除记录
    path('del_rec/<int:pk>',views.delete_recode,name='delete_record'),
    # 推荐页面
    path('recommend',views.RecommendMovieView.as_view(),name='recommend'),
    # 导入物品之间的相似度
    # path('calc_movie_similarity',views.calc_movie_similarity,name='calc_similarity')

]

movie/forms.py
from django import forms
# from django.forms  import ModelForm
from movie.models import User, Movie_rating


class RegisterForm(forms.ModelForm):
    '''注册用的表单'''
    password_repeat = forms.CharField(max_length=256)

    def get_errors(self):
        errors = self.errors.get_json_data()
        errors_lst = []
        for messages in errors.values():
            for message_dict in messages:
                for key, message in message_dict.items():
                    if key == 'message':
                        errors_lst.append(message)
        return errors_lst

    # 普通验证之后的最后一层验证
    # 验证密码
    def clean(self):
        cleaned_data = super(RegisterForm, self).clean()
        pwd = cleaned_data.get('password')
        password_repeat = cleaned_data.get('password_repeat')
        if pwd != password_repeat:
            raise forms.ValidationError(message='两次密码输入不一致！')
        return cleaned_data

    class Meta:
        model = User
        fields = ['name', 'password', 'email']


class LoginForm(forms.ModelForm):
    '''
    用于登录的表单
    '''
    name = forms.CharField(max_length=128)
    remember = forms.IntegerField(required=False)

    class Meta:
        model = User
        fields = ['password']

    def get_errors(self):
        errors = self.errors.get_json_data()
        errors_lst = []
        for messages in errors.values():
            for message_dict in messages:
                for key, message in message_dict.items():
                    if key == 'message':
                        errors_lst.append(message)
        return errors_lst


class CommentForm(forms.ModelForm):
    # 表单验证通过后再验证分数是否为0
    def clean(self):
        cleaned_data = super(CommentForm, self).clean()
        score = cleaned_data.get('score')
        if score == 0:
            raise forms.ValidationError(message='评分不能为空！')
        else:
            return cleaned_data

    class Meta:
        # 电影评分，只记录评分和评论
        model = Movie_rating
        fields = ['score', 'comment']


class MovieRatingForm(forms.ModelForm):
    """电影评分表单"""
    
    def clean(self):
        cleaned_data = super().clean()
        score = cleaned_data.get('score')
        if score == 0:
            raise forms.ValidationError(message='评分不能为空！')
        return cleaned_data
    
    class Meta:
        model = Movie_rating
        fields = ['score', 'comment']

movie/views.py
import csv
import time
import os.path
from math import sqrt
from django.contrib import messages
from django.db.models import Avg, Count, Max
from django.http import HttpResponse, request
from django.shortcuts import render, redirect, reverse
from .forms import RegisterForm, LoginForm, CommentForm
from django.views.generic import View, ListView, DetailView
from .models import User, Movie, Genre, Movie_rating, Movie_similarity, Movie_hot
from django.views.generic import ListView
from movie.models import Movie, User, Movie_rating
from movie.matrix_factorization import generate_recommendations, invalidate_user_cache




# DO NOT MAKE ANY CHANGES
BASE = os.path.dirname(os.path.abspath(__file__))


# 首页
class IndexView(ListView):
    model = Movie
    template_name = 'movie/index.html'
    paginate_by = 15
    context_object_name = 'movies'
    ordering = 'imdb_id'
    page_kwarg = 'p'

    def get_queryset(self):
        # 返回前1000部电影
        return Movie.objects.filter(imdb_id__lte=1000)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(IndexView, self).get_context_data(*kwargs)
        paginator = context.get('paginator')
        page_obj = context.get('page_obj')
        pagination_data = self.get_pagination_data(paginator, page_obj)
        context.update(pagination_data)
        # print(context)
        return context

    def get_pagination_data(self, paginator, page_obj, around_count=2):
        current_page = page_obj.number

        if current_page <= around_count + 2:
            left_pages = range(1, current_page)
            left_has_more = False
        else:
            left_pages = range(current_page - around_count, current_page)
            left_has_more = True

        if current_page >= paginator.num_pages - around_count - 1:
            right_pages = range(current_page + 1, paginator.num_pages + 1)
            right_has_more = False
        else:
            right_pages = range(current_page + 1, current_page + 1 + around_count)
            right_has_more = True
        return {
            'left_pages': left_pages,
            'right_pages': right_pages,
            'current_page': current_page,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more
        }


class PopularMovieView(ListView):
    model = Movie_hot
    template_name = 'movie/hot.html'
    paginate_by = 15
    context_object_name = 'movies'
    page_kwarg = 'p'

    def get_queryset(self):
        # 初始化 计算评分人数最多的100部电影，并保存到数据库中
        # ######################
        # movies = Movie.objects.annotate(nums=Count('movie_rating__score')).order_by('-nums')[:100]
        # print(movies)
        # print(movies.values("nums"))
        # for movie in movies:
            # print(movie,movie.nums)
            # record = Movie_hot(movie=movie, rating_number=movie.nums)
            # record.save()
        # ######################

        hot_movies=Movie_hot.objects.all().values("movie_id")
        # print(hot_movies)
        # for movie in hot_movies:
            # print(movie)
            # print(movie.imdb_id,movie.rating_number)
        # Movie.objects.filter(movie_hot__rating_number=)
        # 一个bug!这里filter出来虽然是正确的100部电影，但是会按照imdb_id排序，导致正确的结果被破坏了！也就是得不到100部热门电影的正确顺序！
        # movies=Movie.objects.filter(id__in=hot_movies.values("imdb_id"))
        # 找出100部热门电影，同时按照评分人数排序
        # 因此我们必须要手动排序一次。另外也不太好用
        movies=Movie.objects.filter(id__in=hot_movies).annotate(nums=Max('movie_hot__rating_number')).order_by('-nums')
        return movies

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PopularMovieView, self).get_context_data(*kwargs)
        paginator = context.get('paginator')
        page_obj = context.get('page_obj')
        pagination_data = self.get_pagination_data(paginator, page_obj)
        context.update(pagination_data)
        # print(context)
        return context

    def get_pagination_data(self, paginator, page_obj, around_count=2):
        current_page = page_obj.number

        if current_page <= around_count + 2:
            left_pages = range(1, current_page)
            left_has_more = False
        else:
            left_pages = range(current_page - around_count, current_page)
            left_has_more = True

        if current_page >= paginator.num_pages - around_count - 1:
            right_pages = range(current_page + 1, paginator.num_pages + 1)
            right_has_more = False
        else:
            right_pages = range(current_page + 1, current_page + 1 + around_count)
            right_has_more = True
        return {
            'left_pages': left_pages,
            'right_pages': right_pages,
            'current_page': current_page,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more
        }

# 分类
class TagView(ListView):
    model = Movie
    template_name = 'movie/tag.html'
    paginate_by = 15
    context_object_name = 'movies'
    # ordering = 'movie_rating__score'
    page_kwarg = 'p'

    def get_queryset(self):
        if 'genre' not in self.request.GET.dict().keys():
            movies = Movie.objects.all()
            return movies[100:200]
        else:
            movies = Movie.objects.filter(genre__name=self.request.GET.dict()['genre'])
            print(movies)
            return movies[:100]

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TagView, self).get_context_data(*kwargs)
        if 'genre' in self.request.GET.dict().keys():
            genre = self.request.GET.dict()['genre']
            context.update({'genre': genre})
        paginator = context.get('paginator')
        page_obj = context.get('page_obj')
        pagination_data = self.get_pagination_data(paginator, page_obj)
        context.update(pagination_data)
        return context

    def get_pagination_data(self, paginator, page_obj, around_count=2):
        current_page = page_obj.number

        if current_page <= around_count + 2:
            left_pages = range(1, current_page)
            left_has_more = False
        else:
            left_pages = range(current_page - around_count, current_page)
            left_has_more = True

        if current_page >= paginator.num_pages - around_count - 1:
            right_pages = range(current_page + 1, paginator.num_pages + 1)
            right_has_more = False
        else:
            right_pages = range(current_page + 1, current_page + 1 + around_count)
            right_has_more = True
        return {
            'left_pages': left_pages,
            'right_pages': right_pages,
            'current_page': current_page,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more
        }

# 搜索
class SearchView(ListView):
    model = Movie
    template_name = 'movie/search.html'
    paginate_by = 15
    context_object_name = 'movies'
    # ordering = 'movie_rating__score'
    page_kwarg = 'p'

    def get_queryset(self):
        movies = Movie.objects.filter(name__icontains=self.request.GET.dict()['keyword'])
        print(movies)
        return movies

    def get_context_data(self, *, object_list=None, **kwargs):
        # self.genre=self.request.GET.dict()['genre']
        context = super(SearchView, self).get_context_data(*kwargs)
        paginator = context.get('paginator')
        page_obj = context.get('page_obj')
        pagination_data = self.get_pagination_data(paginator, page_obj)
        context.update(pagination_data)
        context.update({'keyword': self.request.GET.dict()['keyword']})
        return context

    def get_pagination_data(self, paginator, page_obj, around_count=2):
        current_page = page_obj.number

        if current_page <= around_count + 2:
            left_pages = range(1, current_page)
            left_has_more = False
        else:
            left_pages = range(current_page - around_count, current_page)
            left_has_more = True

        if current_page >= paginator.num_pages - around_count - 1:
            right_pages = range(current_page + 1, paginator.num_pages + 1)
            right_has_more = False
        else:
            right_pages = range(current_page + 1, current_page + 1 + around_count)
            right_has_more = True
        return {
            'left_pages': left_pages,
            'right_pages': right_pages,
            'current_page': current_page,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more
        }


# 注册视图
class RegisterView(View):
    def get(self, request):
        return render(request, 'Signin.html', {'show_register': False})

    def post(self, request):
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'Signin.html', {'register_success': True})
        else:
            errors = form.get_errors()
            # 传递一个标志变量，指示显示注册表单
            return render(request, 'Signin.html', {'register_form': form, 'register_errors': errors, 'show_register': True})

# 登录视图
class LoginView(View):
    def get(self, request):
        return render(request, 'Signin.html')

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data.get('name')
            pwd = form.cleaned_data.get('password')
            user = User.objects.filter(name=name, password=pwd).first()
            if user:
                request.session['user_id'] = user.id
                return redirect(reverse('movie:index'))
            else:
                errors = ['用户名或者密码错误!']
                return render(request, 'Signin.html', {'login_form': form, 'login_errors': errors})
        else:
            errors = form.get_errors()
            return render(request, 'Signin.html', {'login_form': form, 'login_errors': errors})

def UserLogout(request):
    # 登出，立即停止会话
    request.session.set_expiry(-1)

templates/movie/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>电影</title>

    <!-- 网站图标 -->
    <link rel="shortcut icon" href="{% static 'movie/favicon1.ico' %}"/>
    <link rel="bookmark" href="{% static 'movie/favicon1.ico' %}"/>

    <!-- 引入 jQuery（使用官方 CDN 以避免证书问题） -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <!-- 引入 Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

    <!-- 引入 Bootstrap JS -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

<!-- 导航栏 -->
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <!-- 品牌和菜单按钮 -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'movie:index' %}">首页</a>
        </div>

        <!-- 导航栏内容 -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'movie:hot' %}">热门电影</a></li>
                <li><a href="{% url 'movie:tag' %}">电影分类</a></li>
            </ul>

            <!-- 搜索框 -->
            <form class="navbar-form navbar-left" method="GET" action="{% url 'movie:search' %}">
                <div class="form-group">
                    <input type="search" name="keyword" class="form-control" placeholder="Search" required>
                </div>
                <button type="submit" class="btn btn-default">搜索</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                {% if movie_user %}
                    <li><a href="{% url 'movie:history' movie_user.id %}">评分历史</a></li>
                    <li><a href="{% url 'movie:recommend' %}">推荐列表</a></li>
                    <li><a href="{% url 'movie:logout' %}">退出登录</a></li>
                {% else %}
                    <li><a href="{% url 'movie:register' %}">注册/登录</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

{% block content %}
{% endblock %}

</body>
</html>

templates/movie/detail.html
{% extends 'movie/base.html' %}
{% block content %}

    <link href="http://netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://libs.baidu.com/jquery/1.10.2/jquery.min.js"></script>
    <link href="{% static 'css/star-rating.css' %}" media="all" rel="stylesheet" type="text/css"/>
    <script src="{% static 'js/star-rating.js' %}" type="text/javascript"></script>
    <style>
        .poster {
            float: left;
            margin: 3px 12px 0 0;
            overflow: hidden;
            text-align: center;
        }

        .info {
            max-width: 800px;
            margin-top: 15px;
            float: left;
            word-wrap: break-word;
        }
        .smovie{
            display: block;
            float: left;
            font-size: 15px;
            text-align: center;
            margin:0 25px 10px 0;
            width: 200px;
        }
        hr {
            -moz-border-bottom-colors: none;
            -moz-border-image: none;
            -moz-border-left-colors: none;
            -moz-border-right-colors: none;
            -moz-border-top-colors: none;
            border-color: #c9302c;
            border-style: solid none;
            border-width: 1px 0;
            margin: 18px 0;
        }
    </style>
    <!--展示电影信息-->
    <div class="container">
        <div class="poster">
            <a href="{% url 'movie:detail' movie.pk %}" class="item">
                <div class="poster_div">
                    <img src="/static/movie/poster/{{ movie.imdb_id }}.jpg" alt="">
                </div>
            </a>
        </div>
        <div class="info">
            <p>
                电影名：
                {{ movie.name }}
                <span>
                    {% for foo in movie.get_score_int_range %}
                        ❤
                    {% endfor %}
                </span>
                <strong style="color:#e09015">{{ movie.get_score }}</strong>
            </p>
            <p>简介：{{ movie.intro }}</p>
            <p>导演：{{ movie.director }}</p>
            <p>编剧：{{ movie.writers }}</p>
            <p>主演：{{ movie.actors }}</p>
            <p>
                类型：
                {% for genre in movie.get_genre %}
                    <a href="{% url 'movie:tag' %}?genre={{ genre }}">{{ genre }}</a>
                    {% if not forloop.last %}
                        <span>|</span>
                    {% endif %}
                {% endfor %}
            </p>
            <p>时长：{{ movie.time }}</p>
            <p>发行时间：{{ movie.release_time }}</p>
        </div>
    </div>

    <div class="container similarity_movie">
        <br>
        <div class="alert alert-warning" role="alert">喜欢这部电影的人也喜欢...</div>

        {% for movie in similarity_movies %}
            <div class="smovie" {% if forloop.first %} style="margin-left: -6px" {% endif %}>
                <a href="{% url 'movie:detail' movie.pk %}" class="item">
                    <div class="poster_div">
                        <img src="/static/movie/poster/{{ movie.imdb_id }}.jpg" alt="">
                        <p>{{ movie.name }}
                            <strong style="color:#e09015">{{ movie.get_score }}</strong>
                        </p>
                    </div>
                </a>
            </div>

        {% endfor %}

    </div>

    <div class="container">
        <br>
        {% for message in messages %}
            {% if message.tags == 'info' %}
                <div class="alert alert-info" role="alert">{{ message }}</div>
            {% endif %}
        {% endfor %}
    </div>
    {% if login %}

        <div class="container">

            <hr>
            {#       利用js动态生成，依赖这个form#}
            <form class="star" action="" method="post">
                {#            评分组件#}
                <input id="input-2ba" name="score" value="{{ score }}" type="number" class="rating" min="0" max="5"
                       step="0.5"
                       data-stars=5
                       data-symbol="&#xe005;" data-default-caption="{rating} hearts" data-star-captions="{}">
                <label for="comment">评论:</label>
                <textarea class="form-control" name="comment" rows="5" id="comment">{{ comment }}</textarea>
                <br>
                <div class="form-group">
                    {#                提交的按钮#}
                    <button type="submit" class="btn btn-primary" style="margin-right: 10px">提交</button>
                    <button type="reset" class="btn btn-default">清空</button>
                </div>
            </form>
            <br>
            <script>
                jQuery(document).ready(function () {
                    $(".rating-kv").rating();
                });
            </script>
        </div>

    {% endif %}

{% endblock %}

templates/movie/history.html
{% extends 'movie/base.html' %}
{% block content %}
    <script src="{% static 'layer/layer.js' %}"></script>
    <style>
        .poster {
            float: left;
            margin: 3px 12px 0 0;
            overflow: hidden;
            text-align: center;
        }

        .info {
            margin-top: 15px;
            float: left;
            word-wrap: break-word;
        }

        hr {
            -moz-border-bottom-colors: none;
            -moz-border-image: none;
            -moz-border-left-colors: none;
            -moz-border-right-colors: none;
            -moz-border-top-colors: none;
            border-color: #c9302c;
            border-style: solid none;
            border-width: 1px 0;
            margin: 18px 0;
        }
    </style>
    <div class="container">
        {% for message in messages %}
            {% if message.tags == 'info' %}
                <div class="alert alert-success" role="alert">{{ message }}</div>
            {% endif %}
        {% endfor %}
        <div class="alert-success alert" role="alert">评分历史</div>
    </div>

    {% for rating in ratings %}
        <div class="container">
            <div class="poster">
                <a href="{% url 'movie:detail' rating.movie.pk %}" class="item">
                    <div class="poster_div">
                        <img src="/static/movie/poster/{{ rating.movie.imdb_id }}.jpg" alt="">
                    </div>
                </a>
            </div>
            <div class="info">
                <p>
                    电影名：
                    {{ rating.movie.name }}
                    <span>
                    {% for foo in rating.movie.get_score_int_range %}
                        ❤
                    {% endfor %}
                    </span>
                    <strong style="color:#e09015">{{ rating.movie.get_score }}</strong>
                </p>
                <p>
                    我的评分:
                    <strong style="color:#e09015">{{ rating.score }} </strong>
                    我的评论:
                    <strong>{{ rating.comment }}</strong>
                </p>
                {#                <a href="#">#}
                <button type="button" class="btn btn-warning"
                        onclick="confirm_delete('{% url "movie:delete_record" rating.movie.id %}')"><span
                        class="glyphicon glyphicon-trash"></span> 删除评论
                </button>
                {#                </a>#}
            </div>

        </div>
        <div class="container"><hr></div>

    {% endfor %}
    <script>
        // 删除文章的函数
        function confirm_delete(url) {
            // 调用layer弹窗组件
            layer.open({
                // 弹窗标题
                title: "确认删除",
                // 正文
                content: "确认删除这条评论吗？",
                // 点击确定按钮后调用的回调函数
                yes: function (index, layero) {
                    // 指定应当前往的 url
                    {#location.href='{% url "article:article_delete" article.id %}'#}
                    {#location.href = '{% url "movie:delete_record" %}'#}
                    location.href = url
                },
            })
        }
    </script>
    <script>
        window.onkeyup = function (ev) {
            var key = ev.keyCode || ev.which;
            if (key == 27) { //按下Escape
                layer.closeAll(); //疯狂模式，关闭所有层
            }
        }
    </script>
{% endblock %}

templates/movie/hot.html
{% extends 'movie/base.html' %}
{% block content %}
    <style>
        .item {
            display: block;
            float: left;
            font-size: 15px;
            text-align: center;
            margin: 0 25px 10px 0;
            width: 200px;
            position: relative; /* 添加相对定位 */
            overflow: hidden;
        }
        .item .poster_div {
            height: 320px;
            overflow: hidden;
        }
        .item .img_div {
            height: 270px;
            overflow: hidden;
            position: relative; /* 添加相对定位 */
            transition: transform 0.3s ease; /* 添加过渡效果 */
        }
        .item .movie-intro {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            {#background-color: #70ce78;#}
            background-color: #E4A600;
            opacity: 0;
            transition: opacity 0.3s ease;
            color: white;
            padding: 20px; /* 增加内边距，调整内容与边界的距离 */
            box-sizing: border-box;
            display: flex; /* 使用 flexbox 布局 */
            flex-direction: column; /* 垂直排列子元素 */
            justify-content: center; /* 垂直居中 */
            align-items: center; /* 水平居中 */
        }
        .item .img_div:hover {
            transform: scale(1.1); /* 鼠标悬浮时放大 1.1 倍 */
        }
        .item .img_div:hover .movie-intro {
            opacity: 1;
        }
        .movie-intro p {
            font-size: 14px; /* 调整电影简介的字体大小 */
        }
    </style>
    <!--展示电影图片用-->
    <div class="container">
        {% for movie in movies %}
            <a href="{% url 'movie:detail' movie.pk %}" class="item">
                <div class="poster_div">
                    <div class="img_div">
                        <img src="/static/movie/poster/{{ movie.imdb_id }}.jpg" alt="">
                        <div class="movie-intro">
                            <h3>{{ movie.name }}</h3>
                            <p>{{ movie.intro }}</p>
                        </div>
                    </div>
                    <p>{{ movie.name }}
                        <strong style="color:#e09015">{{ movie.get_score }}</strong>
                    </p>
                </div>
            </a>
        {% endfor %}
    </div>

    <!-- nav视图分页用-->
    <nav style="text-align: center;">
        <ul class="pagination">
            {#previous page#}
            {% if page_obj.has_previous %}
                <li><a href="{% url 'movie:hot' %}?p={{ page_obj.previous_page_number }}">上一页</a></li>
            {% else %}
                <li class="disabled"><a href="javascript:void(0);">上一页</a></li>
            {% endif %}

            {% if left_has_more %}
                <li><a href="{% url 'movie:hot' %}?p=1">1</a></li>
                <li><a href="javascript:void(0)">...</a></li>
            {% endif %}

            {#        左边的page#}
            {% for left_page in left_pages %}
                <li><a href="{% url 'movie:hot' %}?p={{ left_page }}">{{ left_page }}</a></li>
            {% endfor %}

            {#    当前的page#}
            <li class="active"><a href="javascript:void(0);">{{ current_page }}</a></li>

            {#     右边的page#}
            {% for right_page in right_pages %}
                <li><a href="{% url 'movie:hot' %}?p={{ right_page }}">{{ right_page }}</a></li>
            {% endfor %}
            {% if right_has_more %}
                <li><a href="javascript:void(0)">...</a></li>
                <li><a href="{% url 'movie:hot' %}?p={{ paginator.num_pages }}">{{ paginator.num_pages }}</a></li>
            {% endif %}
            {#next page#}
            {% if page_obj.has_next %}
                <li><a href="{% url 'movie:hot' %}?p={{ page_obj.next_page_number }}">下一页</a></li>
            {% else %}
                <li class="disabled"><a href="javascript:void(0);">上一页</a></li>
            {% endif %}
        </ul>
    </nav>
{% endblock %}

templates/movie/recommend.html
{% extends 'movie/base.html' %}
{% block content %}
    <style>
        .poster {
            float: left;
            margin: 3px 12px 0 0;
            overflow: hidden;
            text-align: center;
        }

        .info {
            max-width: 800px;
            margin-top: 15px;
            float: left;
            word-wrap: break-word;
            overflow: hidden;
        }

        hr {
            -moz-border-bottom-colors: none;
            -moz-border-image: none;
            -moz-border-left-colors: none;
            -moz-border-right-colors: none;
            -moz-border-top-colors: none;
            border-color: #c9302c;
            border-style: solid none;
            border-width: 1px 0;
            margin: 18px 0;
        }
    </style>
    <div class="container">
        {% for message in messages %}
            {% if message.tags == 'info' %}
                <div class="alert alert-success" role="alert">{{ message }}</div>
            {% endif %}
        {% endfor %}
        
        {% if rating_count_insufficient %}
            <div class="alert alert-warning" role="alert">
                <strong>你的评分历史太少，无法生成个性化推荐。</strong>
                <p>目前你已评分 {{ ratings_count }} 部电影，至少需要评分 10 部电影才能生成个性化推荐。</p>
                <p>还需要评分 {{ ratings_needed }} 部电影。以下是热门电影推荐，你可以先从中选择感兴趣的电影进行评分。</p>
            </div>
        {% else %}
            <div class="alert alert-info" role="alert">这是根据你的评分历史推荐出来的电影</div>
        {% endif %}
    </div>

    {% for movie in movies %}

        <div class="container">
            <div class="poster">
                <a href="{% url 'movie:detail' movie.pk %}" class="item">
                    <div class="poster_div">
                        <img src="/static/movie/poster/{{ movie.imdb_id }}.jpg" alt="">
                    </div>
                </a>
            </div>
            <div class="info">
                <p>
                    电影名：
                    {{ movie.name }}
                </p>
                <span>
                {% for foo in movie.get_score_int_range %}
                    ❤
                {% endfor %}
                </span>
                <strong style="color:#e09015">{{ movie.get_score }}</strong>
                <p style="word-wrap: break-word">
                    简介:
                    {{ movie.intro }}
                </p>
                <p>
                    类型：
                    {% for genre in movie.get_genre %}
                        <a href="{% url 'movie:tag' %}?genre={{ genre }}">{{ genre }}</a>
                        {% if not forloop.last %}
                            <span>|</span>
                        {% endif %}
                    {% endfor %}
                </p>
            </div>
        </div>
        <div class="container">
        <hr>
        </div>

    {% endfor %}
{% endblock %}